import "./globals.css";
import Navbar from "@/components/nav/Navbar";
import Footer from "@/components/footer/Footer";

export const metadata = {
	title: "TMC CCTV and Structured Cabling",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className="w-[100%]">
				<Navbar />
				{children}
				<Footer />
			</body>
		</html>
	);
}
